=== AleksItJv/Web/Lessons/Online_Lessons/Web/Homeworks/01/src/main/java/hw2/factory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="factory" type="factoryType"/>

  <xs:complexType name="factoryType">
    <xs:sequence>
            <xs:element type="candyType" name="candy" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="candyType">
    <xs:sequence>
      <xs:element type="wrapperType" name="wrapper" minOccurs="0" maxOccurs="2"/>
      <xs:element type="coverType" name="cover" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="fillerType" name="filler" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="quantityType" name="quantity"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <!-- *** -->
  <xs:complexType name="wrapperType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="material"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- *** -->
  <xs:complexType name="quantityType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute type="xs:string" name="level"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- *** -->
  <xs:complexType name="coverType">
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <!-- *** -->
  <xs:complexType name="fillerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== AleksItJv/Web/Lessons/Online_Lessons/Web/Homeworks/01/src/main/java/hw2/factory.xml
<?xml version="1.0" encoding="UTF-8" ?>
<factory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="factory.xsd">

    <candy name="red_bogatyr">
        <wrapper>color paper</wrapper>
        <cover>chocolate</cover>
        <filler>chocolate</filler>
        <quantity>2</quantity>
    </candy>

    <candy name="black_and_white">
        <wrapper>black cellophane</wrapper>
        <cover>white chocolate</cover>
        <filler>black fondant</filler>
        <quantity>1</quantity>
    </candy>

    <candy name="karamelka">
        <wrapper>cellophane</wrapper>
        <cover>caramel</cover>
        <filler>caramel</filler>
        <quantity>6</quantity>
    </candy>

</factory>
